# Generated by Django 3.1.4 on 2020-12-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=40, verbose_name='タスク')),
                ('start_day', models.DateField(default=None, null=True, verbose_name='開始日')),
                ('end_day', models.DateField(default=None, null=True, verbose_name='終了日')),
                ('start_time', models.TimeField(default=None, null=True, verbose_name='開始時間')),
                ('end_time', models.TimeField(default=None, null=True, verbose_name='終了時間')),
                ('category', models.CharField(choices=[('PR', 'Private'), ('ST', 'Study'), ('WR', 'Work')], default='PR', max_length=2, verbose_name='カテゴリ')),
                ('completed', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
            },
        ),
    ]
